version: '3.8'
services:
  api-usuarios:
    build: .
    container_name: backend-python
    ports:
      - "8000:8000"
    environment:
      - KEYCLOAK_URL=http://192.168.0.107:8080
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=backend-client
      - KEYCLOAK_CLIENT_SECRET=ZwtmWq33FvwxxUP3XpCehjuK3evaY5pt